name: Deploy Web App sengoku-qa - Node.js

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # Step 3: Install dependencies and build
      - name: Install dependencies and build
        working-directory: ./sengoku-frontend-web
        run: |
          npm install
          npm run build -- --output-path=dist/sengoku-frontend-web/browser

      # Step 4: Package the static files for deployment
      - name: Zip build artifacts
        working-directory: ./sengoku-frontend-web
        run: zip -r release.zip ./dist/sengoku-frontend-web/browser

      # Step 5: Upload artifact for deployment
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: angular-build
          path: ./sengoku-frontend-web/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      # Step 6: Download the build artifact
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: angular-build

      # Step 7: Unzip the artifact
      - name: Unzip build artifact
        run: unzip release.zip

      # Step 8: Deploy to Azure Web App
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_37DD20F03F94456B8EB1FCCD2D496D4C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D6136491267647CAB5DE6340CA1912FC }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E5A2D73ABD6C4DE49F2FB5016C797665 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'sengoku-qa'
          slot-name: 'Production'
          package: ./dist/sengoku-frontend-web/browser
