name: Deploy Web App sengoku-qa - Node.js

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # Step 3: Install dependencies and build
      - name: Install dependencies and build
        working-directory: ./
        run: |
          npm install
          npm run build -- --output-path=./dist/sengoku-frontend-web/browser
          cp web.config ../dist/sengoku-frontend-web/browser/

      # Step 4: Package the build artifacts
      - name: Zip build artifacts
        run: |
          Compress-Archive -Path ./dist/sengoku-frontend-web/browser/* -DestinationPath ./dist/release.zip

      # Step 5: Upload the build artifact
      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: angular-build
          path: ./dist/release.zip

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
    permissions:
      id-token: write # Required for requesting the JWT

    steps:
      # Step 6: Download the build artifact
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: angular-build

      # Step 7: Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_506688A2766241F99C15ADCF922ABE0A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_80AB4FFAE16D4A6B8481B864BF17047E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_336612A37BB44394B7FAE04BF4388A07 }}

      # Step 8: Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'sengoku-qa'
          slot-name: 'Production'
          package: .
